// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file Faults.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_ROS2_INTERFACE_MSG_FAULTS_H_
#define _FAST_DDS_GENERATED_ROS2_INTERFACE_MSG_FAULTS_H_

#include "Header.h"
#include "Fault.h"

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(Faults_SOURCE)
#define Faults_DllAPI __declspec( dllexport )
#else
#define Faults_DllAPI __declspec( dllimport )
#endif // Faults_SOURCE
#else
#define Faults_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define Faults_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace ros2_interface {
    namespace msg {
        /*!
         * @brief This class represents the structure Faults defined by the user in the IDL file.
         * @ingroup FAULTS
         */
        class Faults
        {
        public:

            /*!
             * @brief Default constructor.
             */
            eProsima_user_DllExport Faults();

            /*!
             * @brief Default destructor.
             */
            eProsima_user_DllExport ~Faults();

            /*!
             * @brief Copy constructor.
             * @param x Reference to the object ros2_interface::msg::Faults that will be copied.
             */
            eProsima_user_DllExport Faults(
                    const Faults& x);

            /*!
             * @brief Move constructor.
             * @param x Reference to the object ros2_interface::msg::Faults that will be copied.
             */
            eProsima_user_DllExport Faults(
                    Faults&& x);

            /*!
             * @brief Copy assignment.
             * @param x Reference to the object ros2_interface::msg::Faults that will be copied.
             */
            eProsima_user_DllExport Faults& operator =(
                    const Faults& x);

            /*!
             * @brief Move assignment.
             * @param x Reference to the object ros2_interface::msg::Faults that will be copied.
             */
            eProsima_user_DllExport Faults& operator =(
                    Faults&& x);

            /*!
             * @brief Comparison operator.
             * @param x ros2_interface::msg::Faults object to compare.
             */
            eProsima_user_DllExport bool operator ==(
                    const Faults& x) const;

            /*!
             * @brief Comparison operator.
             * @param x ros2_interface::msg::Faults object to compare.
             */
            eProsima_user_DllExport bool operator !=(
                    const Faults& x) const;

            /*!
             * @brief This function copies the value in member header
             * @param _header New value to be copied in member header
             */
            eProsima_user_DllExport void header(
                    const ros2_interface::msg::Header& _header);

            /*!
             * @brief This function moves the value in member header
             * @param _header New value to be moved in member header
             */
            eProsima_user_DllExport void header(
                    ros2_interface::msg::Header&& _header);

            /*!
             * @brief This function returns a constant reference to member header
             * @return Constant reference to member header
             */
            eProsima_user_DllExport const ros2_interface::msg::Header& header() const;

            /*!
             * @brief This function returns a reference to member header
             * @return Reference to member header
             */
            eProsima_user_DllExport ros2_interface::msg::Header& header();
            /*!
             * @brief This function sets a value in member version
             * @param _version New value for member version
             */
            eProsima_user_DllExport void version(
                    int32_t _version);

            /*!
             * @brief This function returns the value of member version
             * @return Value of member version
             */
            eProsima_user_DllExport int32_t version() const;

            /*!
             * @brief This function returns a reference to member version
             * @return Reference to member version
             */
            eProsima_user_DllExport int32_t& version();

            /*!
             * @brief This function sets a value in member app_id
             * @param _app_id New value for member app_id
             */
            eProsima_user_DllExport void app_id(
                    int32_t _app_id);

            /*!
             * @brief This function returns the value of member app_id
             * @return Value of member app_id
             */
            eProsima_user_DllExport int32_t app_id() const;

            /*!
             * @brief This function returns a reference to member app_id
             * @return Reference to member app_id
             */
            eProsima_user_DllExport int32_t& app_id();

            /*!
             * @brief This function sets a value in member is_active
             * @param _is_active New value for member is_active
             */
            eProsima_user_DllExport void is_active(
                    bool _is_active);

            /*!
             * @brief This function returns the value of member is_active
             * @return Value of member is_active
             */
            eProsima_user_DllExport bool is_active() const;

            /*!
             * @brief This function returns a reference to member is_active
             * @return Reference to member is_active
             */
            eProsima_user_DllExport bool& is_active();

            /*!
             * @brief This function copies the value in member faults
             * @param _faults New value to be copied in member faults
             */
            eProsima_user_DllExport void faults(
                    const std::vector<ros2_interface::msg::Fault>& _faults);

            /*!
             * @brief This function moves the value in member faults
             * @param _faults New value to be moved in member faults
             */
            eProsima_user_DllExport void faults(
                    std::vector<ros2_interface::msg::Fault>&& _faults);

            /*!
             * @brief This function returns a constant reference to member faults
             * @return Constant reference to member faults
             */
            eProsima_user_DllExport const std::vector<ros2_interface::msg::Fault>& faults() const;

            /*!
             * @brief This function returns a reference to member faults
             * @return Reference to member faults
             */
            eProsima_user_DllExport std::vector<ros2_interface::msg::Fault>& faults();

            /*!
             * @brief This function returns the maximum serialized size of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function returns the serialized size of a data depending on the buffer alignment.
             * @param data Data which is calculated its serialized size.
             * @param current_alignment Buffer alignment.
             * @return Serialized size.
             */
            eProsima_user_DllExport static size_t getCdrSerializedSize(
                    const ros2_interface::msg::Faults& data,
                    size_t current_alignment = 0);


            /*!
             * @brief This function serializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serialize(
                    eprosima::fastcdr::Cdr& cdr) const;

            /*!
             * @brief This function deserializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void deserialize(
                    eprosima::fastcdr::Cdr& cdr);



            /*!
             * @brief This function returns the maximum serialized size of the Key of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function tells you if the Key has been defined for this type
             */
            eProsima_user_DllExport static bool isKeyDefined();

            /*!
             * @brief This function serializes the key members of an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serializeKey(
                    eprosima::fastcdr::Cdr& cdr) const;

        private:

            ros2_interface::msg::Header m_header;
            int32_t m_version;
            int32_t m_app_id;
            bool m_is_active;
            std::vector<ros2_interface::msg::Fault> m_faults;
        };
    } // namespace msg
} // namespace ros2_interface

#endif // _FAST_DDS_GENERATED_ROS2_INTERFACE_MSG_FAULTS_H_