// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file GuideRoad.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_ROS2_INTERFACE_MSG_GUIDEROAD_H_
#define _FAST_DDS_GENERATED_ROS2_INTERFACE_MSG_GUIDEROAD_H_

#include "CurvatureInfo.h"

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(GuideRoad_SOURCE)
#define GuideRoad_DllAPI __declspec( dllexport )
#else
#define GuideRoad_DllAPI __declspec( dllimport )
#endif // GuideRoad_SOURCE
#else
#define GuideRoad_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define GuideRoad_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace ros2_interface {
    namespace msg {
        /*!
         * @brief This class represents the structure GuideRoad defined by the user in the IDL file.
         * @ingroup GUIDEROAD
         */
        class GuideRoad
        {
        public:

            /*!
             * @brief Default constructor.
             */
            eProsima_user_DllExport GuideRoad();

            /*!
             * @brief Default destructor.
             */
            eProsima_user_DllExport ~GuideRoad();

            /*!
             * @brief Copy constructor.
             * @param x Reference to the object ros2_interface::msg::GuideRoad that will be copied.
             */
            eProsima_user_DllExport GuideRoad(
                    const GuideRoad& x);

            /*!
             * @brief Move constructor.
             * @param x Reference to the object ros2_interface::msg::GuideRoad that will be copied.
             */
            eProsima_user_DllExport GuideRoad(
                    GuideRoad&& x);

            /*!
             * @brief Copy assignment.
             * @param x Reference to the object ros2_interface::msg::GuideRoad that will be copied.
             */
            eProsima_user_DllExport GuideRoad& operator =(
                    const GuideRoad& x);

            /*!
             * @brief Move assignment.
             * @param x Reference to the object ros2_interface::msg::GuideRoad that will be copied.
             */
            eProsima_user_DllExport GuideRoad& operator =(
                    GuideRoad&& x);

            /*!
             * @brief Comparison operator.
             * @param x ros2_interface::msg::GuideRoad object to compare.
             */
            eProsima_user_DllExport bool operator ==(
                    const GuideRoad& x) const;

            /*!
             * @brief Comparison operator.
             * @param x ros2_interface::msg::GuideRoad object to compare.
             */
            eProsima_user_DllExport bool operator !=(
                    const GuideRoad& x) const;

            /*!
             * @brief This function sets a value in member road_id
             * @param _road_id New value for member road_id
             */
            eProsima_user_DllExport void road_id(
                    int64_t _road_id);

            /*!
             * @brief This function returns the value of member road_id
             * @return Value of member road_id
             */
            eProsima_user_DllExport int64_t road_id() const;

            /*!
             * @brief This function returns a reference to member road_id
             * @return Reference to member road_id
             */
            eProsima_user_DllExport int64_t& road_id();

            /*!
             * @brief This function sets a value in member road_type
             * @param _road_type New value for member road_type
             */
            eProsima_user_DllExport void road_type(
                    int8_t _road_type);

            /*!
             * @brief This function returns the value of member road_type
             * @return Value of member road_type
             */
            eProsima_user_DllExport int8_t road_type() const;

            /*!
             * @brief This function returns a reference to member road_type
             * @return Reference to member road_type
             */
            eProsima_user_DllExport int8_t& road_type();

            /*!
             * @brief This function sets a value in member turn_type
             * @param _turn_type New value for member turn_type
             */
            eProsima_user_DllExport void turn_type(
                    int8_t _turn_type);

            /*!
             * @brief This function returns the value of member turn_type
             * @return Value of member turn_type
             */
            eProsima_user_DllExport int8_t turn_type() const;

            /*!
             * @brief This function returns a reference to member turn_type
             * @return Reference to member turn_type
             */
            eProsima_user_DllExport int8_t& turn_type();

            /*!
             * @brief This function sets a value in member avg_curvature
             * @param _avg_curvature New value for member avg_curvature
             */
            eProsima_user_DllExport void avg_curvature(
                    double _avg_curvature);

            /*!
             * @brief This function returns the value of member avg_curvature
             * @return Value of member avg_curvature
             */
            eProsima_user_DllExport double avg_curvature() const;

            /*!
             * @brief This function returns a reference to member avg_curvature
             * @return Reference to member avg_curvature
             */
            eProsima_user_DllExport double& avg_curvature();

            /*!
             * @brief This function sets a value in member curvature_size
             * @param _curvature_size New value for member curvature_size
             */
            eProsima_user_DllExport void curvature_size(
                    int32_t _curvature_size);

            /*!
             * @brief This function returns the value of member curvature_size
             * @return Value of member curvature_size
             */
            eProsima_user_DllExport int32_t curvature_size() const;

            /*!
             * @brief This function returns a reference to member curvature_size
             * @return Reference to member curvature_size
             */
            eProsima_user_DllExport int32_t& curvature_size();

            /*!
             * @brief This function copies the value in member curvature
             * @param _curvature New value to be copied in member curvature
             */
            eProsima_user_DllExport void curvature(
                    const std::vector<ros2_interface::msg::CurvatureInfo>& _curvature);

            /*!
             * @brief This function moves the value in member curvature
             * @param _curvature New value to be moved in member curvature
             */
            eProsima_user_DllExport void curvature(
                    std::vector<ros2_interface::msg::CurvatureInfo>&& _curvature);

            /*!
             * @brief This function returns a constant reference to member curvature
             * @return Constant reference to member curvature
             */
            eProsima_user_DllExport const std::vector<ros2_interface::msg::CurvatureInfo>& curvature() const;

            /*!
             * @brief This function returns a reference to member curvature
             * @return Reference to member curvature
             */
            eProsima_user_DllExport std::vector<ros2_interface::msg::CurvatureInfo>& curvature();

            /*!
             * @brief This function returns the maximum serialized size of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function returns the serialized size of a data depending on the buffer alignment.
             * @param data Data which is calculated its serialized size.
             * @param current_alignment Buffer alignment.
             * @return Serialized size.
             */
            eProsima_user_DllExport static size_t getCdrSerializedSize(
                    const ros2_interface::msg::GuideRoad& data,
                    size_t current_alignment = 0);


            /*!
             * @brief This function serializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serialize(
                    eprosima::fastcdr::Cdr& cdr) const;

            /*!
             * @brief This function deserializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void deserialize(
                    eprosima::fastcdr::Cdr& cdr);



            /*!
             * @brief This function returns the maximum serialized size of the Key of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function tells you if the Key has been defined for this type
             */
            eProsima_user_DllExport static bool isKeyDefined();

            /*!
             * @brief This function serializes the key members of an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serializeKey(
                    eprosima::fastcdr::Cdr& cdr) const;

        private:

            int64_t m_road_id;
            int8_t m_road_type;
            int8_t m_turn_type;
            double m_avg_curvature;
            int32_t m_curvature_size;
            std::vector<ros2_interface::msg::CurvatureInfo> m_curvature;
        };
    } // namespace msg
} // namespace ros2_interface

#endif // _FAST_DDS_GENERATED_ROS2_INTERFACE_MSG_GUIDEROAD_H_