// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file HMIObuCmd.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "HMIObuCmd.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

ros2_interface::msg::HMIObuCmd::HMIObuCmd()
{
    // m_code com.eprosima.idl.parser.typecode.PrimitiveTypeCode@24c4ddae
    m_code = 0;
    // m_val com.eprosima.idl.parser.typecode.PrimitiveTypeCode@37fb0bed
    m_val = 0;

}

ros2_interface::msg::HMIObuCmd::~HMIObuCmd()
{


}

ros2_interface::msg::HMIObuCmd::HMIObuCmd(
        const HMIObuCmd& x)
{
    m_code = x.m_code;
    m_val = x.m_val;
}

ros2_interface::msg::HMIObuCmd::HMIObuCmd(
        HMIObuCmd&& x)
{
    m_code = x.m_code;
    m_val = x.m_val;
}

ros2_interface::msg::HMIObuCmd& ros2_interface::msg::HMIObuCmd::operator =(
        const HMIObuCmd& x)
{

    m_code = x.m_code;
    m_val = x.m_val;

    return *this;
}

ros2_interface::msg::HMIObuCmd& ros2_interface::msg::HMIObuCmd::operator =(
        HMIObuCmd&& x)
{

    m_code = x.m_code;
    m_val = x.m_val;

    return *this;
}

bool ros2_interface::msg::HMIObuCmd::operator ==(
        const HMIObuCmd& x) const
{

    return (m_code == x.m_code && m_val == x.m_val);
}

bool ros2_interface::msg::HMIObuCmd::operator !=(
        const HMIObuCmd& x) const
{
    return !(*this == x);
}

size_t ros2_interface::msg::HMIObuCmd::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

size_t ros2_interface::msg::HMIObuCmd::getCdrSerializedSize(
        const ros2_interface::msg::HMIObuCmd& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

void ros2_interface::msg::HMIObuCmd::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_code;
    scdr << m_val;

}

void ros2_interface::msg::HMIObuCmd::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_code;
    dcdr >> m_val;
}

/*!
 * @brief This function sets a value in member code
 * @param _code New value for member code
 */
void ros2_interface::msg::HMIObuCmd::code(
        int32_t _code)
{
    m_code = _code;
}

/*!
 * @brief This function returns the value of member code
 * @return Value of member code
 */
int32_t ros2_interface::msg::HMIObuCmd::code() const
{
    return m_code;
}

/*!
 * @brief This function returns a reference to member code
 * @return Reference to member code
 */
int32_t& ros2_interface::msg::HMIObuCmd::code()
{
    return m_code;
}

/*!
 * @brief This function sets a value in member val
 * @param _val New value for member val
 */
void ros2_interface::msg::HMIObuCmd::val(
        int32_t _val)
{
    m_val = _val;
}

/*!
 * @brief This function returns the value of member val
 * @return Value of member val
 */
int32_t ros2_interface::msg::HMIObuCmd::val() const
{
    return m_val;
}

/*!
 * @brief This function returns a reference to member val
 * @return Reference to member val
 */
int32_t& ros2_interface::msg::HMIObuCmd::val()
{
    return m_val;
}


size_t ros2_interface::msg::HMIObuCmd::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;





    return current_align;
}

bool ros2_interface::msg::HMIObuCmd::isKeyDefined()
{
    return false;
}

void ros2_interface::msg::HMIObuCmd::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
      
}


