// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file HMIParkingInfoList.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "HMIParkingInfoList.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

ros2_interface::msg::HMIParkingInfoList::HMIParkingInfoList()
{
    // m_header com.eprosima.fastdds.idl.parser.typecode.StructTypeCode@b83a9be

    // m_parking_info com.eprosima.idl.parser.typecode.SequenceTypeCode@2609b277

    // m_parking_out_enable com.eprosima.idl.parser.typecode.PrimitiveTypeCode@1fd14d74
    m_parking_out_enable = false;
    // m_parking_out_direction com.eprosima.idl.parser.typecode.PrimitiveTypeCode@563e4951
    m_parking_out_direction = 0;
    // m_parking_out_id com.eprosima.idl.parser.typecode.PrimitiveTypeCode@4066c471
    m_parking_out_id = 0;

}

ros2_interface::msg::HMIParkingInfoList::~HMIParkingInfoList()
{





}

ros2_interface::msg::HMIParkingInfoList::HMIParkingInfoList(
        const HMIParkingInfoList& x)
{
    m_header = x.m_header;
    m_parking_info = x.m_parking_info;
    m_parking_out_enable = x.m_parking_out_enable;
    m_parking_out_direction = x.m_parking_out_direction;
    m_parking_out_id = x.m_parking_out_id;
}

ros2_interface::msg::HMIParkingInfoList::HMIParkingInfoList(
        HMIParkingInfoList&& x)
{
    m_header = std::move(x.m_header);
    m_parking_info = std::move(x.m_parking_info);
    m_parking_out_enable = x.m_parking_out_enable;
    m_parking_out_direction = x.m_parking_out_direction;
    m_parking_out_id = x.m_parking_out_id;
}

ros2_interface::msg::HMIParkingInfoList& ros2_interface::msg::HMIParkingInfoList::operator =(
        const HMIParkingInfoList& x)
{

    m_header = x.m_header;
    m_parking_info = x.m_parking_info;
    m_parking_out_enable = x.m_parking_out_enable;
    m_parking_out_direction = x.m_parking_out_direction;
    m_parking_out_id = x.m_parking_out_id;

    return *this;
}

ros2_interface::msg::HMIParkingInfoList& ros2_interface::msg::HMIParkingInfoList::operator =(
        HMIParkingInfoList&& x)
{

    m_header = std::move(x.m_header);
    m_parking_info = std::move(x.m_parking_info);
    m_parking_out_enable = x.m_parking_out_enable;
    m_parking_out_direction = x.m_parking_out_direction;
    m_parking_out_id = x.m_parking_out_id;

    return *this;
}

bool ros2_interface::msg::HMIParkingInfoList::operator ==(
        const HMIParkingInfoList& x) const
{

    return (m_header == x.m_header && m_parking_info == x.m_parking_info && m_parking_out_enable == x.m_parking_out_enable && m_parking_out_direction == x.m_parking_out_direction && m_parking_out_id == x.m_parking_out_id);
}

bool ros2_interface::msg::HMIParkingInfoList::operator !=(
        const HMIParkingInfoList& x) const
{
    return !(*this == x);
}

size_t ros2_interface::msg::HMIParkingInfoList::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += ros2_interface::msg::Header::getMaxCdrSerializedSize(current_alignment);
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    for(size_t a = 0; a < 100; ++a)
    {
        current_alignment += ros2_interface::msg::HMIParkingInfo::getMaxCdrSerializedSize(current_alignment);}

    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

size_t ros2_interface::msg::HMIParkingInfoList::getCdrSerializedSize(
        const ros2_interface::msg::HMIParkingInfoList& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += ros2_interface::msg::Header::getCdrSerializedSize(data.header(), current_alignment);
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    for(size_t a = 0; a < data.parking_info().size(); ++a)
    {
        current_alignment += ros2_interface::msg::HMIParkingInfo::getCdrSerializedSize(data.parking_info().at(a), current_alignment);}

    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);



    return current_alignment - initial_alignment;
}

void ros2_interface::msg::HMIParkingInfoList::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_header;
    scdr << m_parking_info;
    scdr << m_parking_out_enable;
    scdr << m_parking_out_direction;
    scdr << m_parking_out_id;

}

void ros2_interface::msg::HMIParkingInfoList::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_header;
    dcdr >> m_parking_info;
    dcdr >> m_parking_out_enable;
    dcdr >> m_parking_out_direction;
    dcdr >> m_parking_out_id;
}

/*!
 * @brief This function copies the value in member header
 * @param _header New value to be copied in member header
 */
void ros2_interface::msg::HMIParkingInfoList::header(
        const ros2_interface::msg::Header& _header)
{
    m_header = _header;
}

/*!
 * @brief This function moves the value in member header
 * @param _header New value to be moved in member header
 */
void ros2_interface::msg::HMIParkingInfoList::header(
        ros2_interface::msg::Header&& _header)
{
    m_header = std::move(_header);
}

/*!
 * @brief This function returns a constant reference to member header
 * @return Constant reference to member header
 */
const ros2_interface::msg::Header& ros2_interface::msg::HMIParkingInfoList::header() const
{
    return m_header;
}

/*!
 * @brief This function returns a reference to member header
 * @return Reference to member header
 */
ros2_interface::msg::Header& ros2_interface::msg::HMIParkingInfoList::header()
{
    return m_header;
}
/*!
 * @brief This function copies the value in member parking_info
 * @param _parking_info New value to be copied in member parking_info
 */
void ros2_interface::msg::HMIParkingInfoList::parking_info(
        const std::vector<ros2_interface::msg::HMIParkingInfo>& _parking_info)
{
    m_parking_info = _parking_info;
}

/*!
 * @brief This function moves the value in member parking_info
 * @param _parking_info New value to be moved in member parking_info
 */
void ros2_interface::msg::HMIParkingInfoList::parking_info(
        std::vector<ros2_interface::msg::HMIParkingInfo>&& _parking_info)
{
    m_parking_info = std::move(_parking_info);
}

/*!
 * @brief This function returns a constant reference to member parking_info
 * @return Constant reference to member parking_info
 */
const std::vector<ros2_interface::msg::HMIParkingInfo>& ros2_interface::msg::HMIParkingInfoList::parking_info() const
{
    return m_parking_info;
}

/*!
 * @brief This function returns a reference to member parking_info
 * @return Reference to member parking_info
 */
std::vector<ros2_interface::msg::HMIParkingInfo>& ros2_interface::msg::HMIParkingInfoList::parking_info()
{
    return m_parking_info;
}
/*!
 * @brief This function sets a value in member parking_out_enable
 * @param _parking_out_enable New value for member parking_out_enable
 */
void ros2_interface::msg::HMIParkingInfoList::parking_out_enable(
        bool _parking_out_enable)
{
    m_parking_out_enable = _parking_out_enable;
}

/*!
 * @brief This function returns the value of member parking_out_enable
 * @return Value of member parking_out_enable
 */
bool ros2_interface::msg::HMIParkingInfoList::parking_out_enable() const
{
    return m_parking_out_enable;
}

/*!
 * @brief This function returns a reference to member parking_out_enable
 * @return Reference to member parking_out_enable
 */
bool& ros2_interface::msg::HMIParkingInfoList::parking_out_enable()
{
    return m_parking_out_enable;
}

/*!
 * @brief This function sets a value in member parking_out_direction
 * @param _parking_out_direction New value for member parking_out_direction
 */
void ros2_interface::msg::HMIParkingInfoList::parking_out_direction(
        int32_t _parking_out_direction)
{
    m_parking_out_direction = _parking_out_direction;
}

/*!
 * @brief This function returns the value of member parking_out_direction
 * @return Value of member parking_out_direction
 */
int32_t ros2_interface::msg::HMIParkingInfoList::parking_out_direction() const
{
    return m_parking_out_direction;
}

/*!
 * @brief This function returns a reference to member parking_out_direction
 * @return Reference to member parking_out_direction
 */
int32_t& ros2_interface::msg::HMIParkingInfoList::parking_out_direction()
{
    return m_parking_out_direction;
}

/*!
 * @brief This function sets a value in member parking_out_id
 * @param _parking_out_id New value for member parking_out_id
 */
void ros2_interface::msg::HMIParkingInfoList::parking_out_id(
        int32_t _parking_out_id)
{
    m_parking_out_id = _parking_out_id;
}

/*!
 * @brief This function returns the value of member parking_out_id
 * @return Value of member parking_out_id
 */
int32_t ros2_interface::msg::HMIParkingInfoList::parking_out_id() const
{
    return m_parking_out_id;
}

/*!
 * @brief This function returns a reference to member parking_out_id
 * @return Reference to member parking_out_id
 */
int32_t& ros2_interface::msg::HMIParkingInfoList::parking_out_id()
{
    return m_parking_out_id;
}


size_t ros2_interface::msg::HMIParkingInfoList::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;








    return current_align;
}

bool ros2_interface::msg::HMIParkingInfoList::isKeyDefined()
{
    return false;
}

void ros2_interface::msg::HMIParkingInfoList::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
         
}


