// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file StopPoint.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_ROS2_INTERFACE_MSG_STOPPOINT_H_
#define _FAST_DDS_GENERATED_ROS2_INTERFACE_MSG_STOPPOINT_H_

#include "Point3D.h"

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(StopPoint_SOURCE)
#define StopPoint_DllAPI __declspec( dllexport )
#else
#define StopPoint_DllAPI __declspec( dllimport )
#endif // StopPoint_SOURCE
#else
#define StopPoint_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define StopPoint_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace ros2_interface {
    namespace msg {
        /*!
         * @brief This class represents the structure StopPoint defined by the user in the IDL file.
         * @ingroup STOPPOINT
         */
        class StopPoint
        {
        public:

            /*!
             * @brief Default constructor.
             */
            eProsima_user_DllExport StopPoint();

            /*!
             * @brief Default destructor.
             */
            eProsima_user_DllExport ~StopPoint();

            /*!
             * @brief Copy constructor.
             * @param x Reference to the object ros2_interface::msg::StopPoint that will be copied.
             */
            eProsima_user_DllExport StopPoint(
                    const StopPoint& x);

            /*!
             * @brief Move constructor.
             * @param x Reference to the object ros2_interface::msg::StopPoint that will be copied.
             */
            eProsima_user_DllExport StopPoint(
                    StopPoint&& x);

            /*!
             * @brief Copy assignment.
             * @param x Reference to the object ros2_interface::msg::StopPoint that will be copied.
             */
            eProsima_user_DllExport StopPoint& operator =(
                    const StopPoint& x);

            /*!
             * @brief Move assignment.
             * @param x Reference to the object ros2_interface::msg::StopPoint that will be copied.
             */
            eProsima_user_DllExport StopPoint& operator =(
                    StopPoint&& x);

            /*!
             * @brief Comparison operator.
             * @param x ros2_interface::msg::StopPoint object to compare.
             */
            eProsima_user_DllExport bool operator ==(
                    const StopPoint& x) const;

            /*!
             * @brief Comparison operator.
             * @param x ros2_interface::msg::StopPoint object to compare.
             */
            eProsima_user_DllExport bool operator !=(
                    const StopPoint& x) const;

            /*!
             * @brief This function copies the value in member point
             * @param _point New value to be copied in member point
             */
            eProsima_user_DllExport void point(
                    const ros2_interface::msg::Point3D& _point);

            /*!
             * @brief This function moves the value in member point
             * @param _point New value to be moved in member point
             */
            eProsima_user_DllExport void point(
                    ros2_interface::msg::Point3D&& _point);

            /*!
             * @brief This function returns a constant reference to member point
             * @return Constant reference to member point
             */
            eProsima_user_DllExport const ros2_interface::msg::Point3D& point() const;

            /*!
             * @brief This function returns a reference to member point
             * @return Reference to member point
             */
            eProsima_user_DllExport ros2_interface::msg::Point3D& point();
            /*!
             * @brief This function sets a value in member theta
             * @param _theta New value for member theta
             */
            eProsima_user_DllExport void theta(
                    double _theta);

            /*!
             * @brief This function returns the value of member theta
             * @return Value of member theta
             */
            eProsima_user_DllExport double theta() const;

            /*!
             * @brief This function returns a reference to member theta
             * @return Reference to member theta
             */
            eProsima_user_DllExport double& theta();

            /*!
             * @brief This function sets a value in member type
             * @param _type New value for member type
             */
            eProsima_user_DllExport void type(
                    int8_t _type);

            /*!
             * @brief This function returns the value of member type
             * @return Value of member type
             */
            eProsima_user_DllExport int8_t type() const;

            /*!
             * @brief This function returns a reference to member type
             * @return Reference to member type
             */
            eProsima_user_DllExport int8_t& type();

            /*!
             * @brief This function sets a value in member stop_distance
             * @param _stop_distance New value for member stop_distance
             */
            eProsima_user_DllExport void stop_distance(
                    double _stop_distance);

            /*!
             * @brief This function returns the value of member stop_distance
             * @return Value of member stop_distance
             */
            eProsima_user_DllExport double stop_distance() const;

            /*!
             * @brief This function returns a reference to member stop_distance
             * @return Reference to member stop_distance
             */
            eProsima_user_DllExport double& stop_distance();


            /*!
             * @brief This function returns the maximum serialized size of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function returns the serialized size of a data depending on the buffer alignment.
             * @param data Data which is calculated its serialized size.
             * @param current_alignment Buffer alignment.
             * @return Serialized size.
             */
            eProsima_user_DllExport static size_t getCdrSerializedSize(
                    const ros2_interface::msg::StopPoint& data,
                    size_t current_alignment = 0);


            /*!
             * @brief This function serializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serialize(
                    eprosima::fastcdr::Cdr& cdr) const;

            /*!
             * @brief This function deserializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void deserialize(
                    eprosima::fastcdr::Cdr& cdr);



            /*!
             * @brief This function returns the maximum serialized size of the Key of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function tells you if the Key has been defined for this type
             */
            eProsima_user_DllExport static bool isKeyDefined();

            /*!
             * @brief This function serializes the key members of an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serializeKey(
                    eprosima::fastcdr::Cdr& cdr) const;

        private:

            ros2_interface::msg::Point3D m_point;
            double m_theta;
            int8_t m_type;
            double m_stop_distance;
        };
    } // namespace msg
} // namespace ros2_interface

#endif // _FAST_DDS_GENERATED_ROS2_INTERFACE_MSG_STOPPOINT_H_