// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file UltrasonicObstacle.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_ROS2_INTERFACE_MSG_ULTRASONICOBSTACLE_H_
#define _FAST_DDS_GENERATED_ROS2_INTERFACE_MSG_ULTRASONICOBSTACLE_H_


#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(UltrasonicObstacle_SOURCE)
#define UltrasonicObstacle_DllAPI __declspec( dllexport )
#else
#define UltrasonicObstacle_DllAPI __declspec( dllimport )
#endif // UltrasonicObstacle_SOURCE
#else
#define UltrasonicObstacle_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define UltrasonicObstacle_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace ros2_interface {
    namespace msg {
        /*!
         * @brief This class represents the structure UltrasonicObstacle defined by the user in the IDL file.
         * @ingroup ULTRASONICOBSTACLE
         */
        class UltrasonicObstacle
        {
        public:

            /*!
             * @brief Default constructor.
             */
            eProsima_user_DllExport UltrasonicObstacle();

            /*!
             * @brief Default destructor.
             */
            eProsima_user_DllExport ~UltrasonicObstacle();

            /*!
             * @brief Copy constructor.
             * @param x Reference to the object ros2_interface::msg::UltrasonicObstacle that will be copied.
             */
            eProsima_user_DllExport UltrasonicObstacle(
                    const UltrasonicObstacle& x);

            /*!
             * @brief Move constructor.
             * @param x Reference to the object ros2_interface::msg::UltrasonicObstacle that will be copied.
             */
            eProsima_user_DllExport UltrasonicObstacle(
                    UltrasonicObstacle&& x);

            /*!
             * @brief Copy assignment.
             * @param x Reference to the object ros2_interface::msg::UltrasonicObstacle that will be copied.
             */
            eProsima_user_DllExport UltrasonicObstacle& operator =(
                    const UltrasonicObstacle& x);

            /*!
             * @brief Move assignment.
             * @param x Reference to the object ros2_interface::msg::UltrasonicObstacle that will be copied.
             */
            eProsima_user_DllExport UltrasonicObstacle& operator =(
                    UltrasonicObstacle&& x);

            /*!
             * @brief Comparison operator.
             * @param x ros2_interface::msg::UltrasonicObstacle object to compare.
             */
            eProsima_user_DllExport bool operator ==(
                    const UltrasonicObstacle& x) const;

            /*!
             * @brief Comparison operator.
             * @param x ros2_interface::msg::UltrasonicObstacle object to compare.
             */
            eProsima_user_DllExport bool operator !=(
                    const UltrasonicObstacle& x) const;

            /*!
             * @brief This function sets a value in member id
             * @param _id New value for member id
             */
            eProsima_user_DllExport void id(
                    int32_t _id);

            /*!
             * @brief This function returns the value of member id
             * @return Value of member id
             */
            eProsima_user_DllExport int32_t id() const;

            /*!
             * @brief This function returns a reference to member id
             * @return Reference to member id
             */
            eProsima_user_DllExport int32_t& id();

            /*!
             * @brief This function sets a value in member range
             * @param _range New value for member range
             */
            eProsima_user_DllExport void range(
                    double _range);

            /*!
             * @brief This function returns the value of member range
             * @return Value of member range
             */
            eProsima_user_DllExport double range() const;

            /*!
             * @brief This function returns a reference to member range
             * @return Reference to member range
             */
            eProsima_user_DllExport double& range();


            /*!
             * @brief This function returns the maximum serialized size of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function returns the serialized size of a data depending on the buffer alignment.
             * @param data Data which is calculated its serialized size.
             * @param current_alignment Buffer alignment.
             * @return Serialized size.
             */
            eProsima_user_DllExport static size_t getCdrSerializedSize(
                    const ros2_interface::msg::UltrasonicObstacle& data,
                    size_t current_alignment = 0);


            /*!
             * @brief This function serializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serialize(
                    eprosima::fastcdr::Cdr& cdr) const;

            /*!
             * @brief This function deserializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void deserialize(
                    eprosima::fastcdr::Cdr& cdr);



            /*!
             * @brief This function returns the maximum serialized size of the Key of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function tells you if the Key has been defined for this type
             */
            eProsima_user_DllExport static bool isKeyDefined();

            /*!
             * @brief This function serializes the key members of an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serializeKey(
                    eprosima::fastcdr::Cdr& cdr) const;

        private:

            int32_t m_id;
            double m_range;
        };
    } // namespace msg
} // namespace ros2_interface

#endif // _FAST_DDS_GENERATED_ROS2_INTERFACE_MSG_ULTRASONICOBSTACLE_H_