// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file UssParkingInfo.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _FAST_DDS_GENERATED_ROS2_INTERFACE_MSG_USSPARKINGINFO_H_
#define _FAST_DDS_GENERATED_ROS2_INTERFACE_MSG_USSPARKINGINFO_H_

#include "Header.h"
#include "Point3D.h"

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(UssParkingInfo_SOURCE)
#define UssParkingInfo_DllAPI __declspec( dllexport )
#else
#define UssParkingInfo_DllAPI __declspec( dllimport )
#endif // UssParkingInfo_SOURCE
#else
#define UssParkingInfo_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define UssParkingInfo_DllAPI
#endif // _WIN32

namespace eprosima {
namespace fastcdr {
class Cdr;
} // namespace fastcdr
} // namespace eprosima


namespace ros2_interface {
    namespace msg {
        /*!
         * @brief This class represents the structure UssParkingInfo defined by the user in the IDL file.
         * @ingroup USSPARKINGINFO
         */
        class UssParkingInfo
        {
        public:

            /*!
             * @brief Default constructor.
             */
            eProsima_user_DllExport UssParkingInfo();

            /*!
             * @brief Default destructor.
             */
            eProsima_user_DllExport ~UssParkingInfo();

            /*!
             * @brief Copy constructor.
             * @param x Reference to the object ros2_interface::msg::UssParkingInfo that will be copied.
             */
            eProsima_user_DllExport UssParkingInfo(
                    const UssParkingInfo& x);

            /*!
             * @brief Move constructor.
             * @param x Reference to the object ros2_interface::msg::UssParkingInfo that will be copied.
             */
            eProsima_user_DllExport UssParkingInfo(
                    UssParkingInfo&& x);

            /*!
             * @brief Copy assignment.
             * @param x Reference to the object ros2_interface::msg::UssParkingInfo that will be copied.
             */
            eProsima_user_DllExport UssParkingInfo& operator =(
                    const UssParkingInfo& x);

            /*!
             * @brief Move assignment.
             * @param x Reference to the object ros2_interface::msg::UssParkingInfo that will be copied.
             */
            eProsima_user_DllExport UssParkingInfo& operator =(
                    UssParkingInfo&& x);

            /*!
             * @brief Comparison operator.
             * @param x ros2_interface::msg::UssParkingInfo object to compare.
             */
            eProsima_user_DllExport bool operator ==(
                    const UssParkingInfo& x) const;

            /*!
             * @brief Comparison operator.
             * @param x ros2_interface::msg::UssParkingInfo object to compare.
             */
            eProsima_user_DllExport bool operator !=(
                    const UssParkingInfo& x) const;

            /*!
             * @brief This function copies the value in member header
             * @param _header New value to be copied in member header
             */
            eProsima_user_DllExport void header(
                    const ros2_interface::msg::Header& _header);

            /*!
             * @brief This function moves the value in member header
             * @param _header New value to be moved in member header
             */
            eProsima_user_DllExport void header(
                    ros2_interface::msg::Header&& _header);

            /*!
             * @brief This function returns a constant reference to member header
             * @return Constant reference to member header
             */
            eProsima_user_DllExport const ros2_interface::msg::Header& header() const;

            /*!
             * @brief This function returns a reference to member header
             * @return Reference to member header
             */
            eProsima_user_DllExport ros2_interface::msg::Header& header();
            /*!
             * @brief This function sets a value in member uss_parking_type
             * @param _uss_parking_type New value for member uss_parking_type
             */
            eProsima_user_DllExport void uss_parking_type(
                    int32_t _uss_parking_type);

            /*!
             * @brief This function returns the value of member uss_parking_type
             * @return Value of member uss_parking_type
             */
            eProsima_user_DllExport int32_t uss_parking_type() const;

            /*!
             * @brief This function returns a reference to member uss_parking_type
             * @return Reference to member uss_parking_type
             */
            eProsima_user_DllExport int32_t& uss_parking_type();

            /*!
             * @brief This function copies the value in member parking_point0
             * @param _parking_point0 New value to be copied in member parking_point0
             */
            eProsima_user_DllExport void parking_point0(
                    const ros2_interface::msg::Point3D& _parking_point0);

            /*!
             * @brief This function moves the value in member parking_point0
             * @param _parking_point0 New value to be moved in member parking_point0
             */
            eProsima_user_DllExport void parking_point0(
                    ros2_interface::msg::Point3D&& _parking_point0);

            /*!
             * @brief This function returns a constant reference to member parking_point0
             * @return Constant reference to member parking_point0
             */
            eProsima_user_DllExport const ros2_interface::msg::Point3D& parking_point0() const;

            /*!
             * @brief This function returns a reference to member parking_point0
             * @return Reference to member parking_point0
             */
            eProsima_user_DllExport ros2_interface::msg::Point3D& parking_point0();
            /*!
             * @brief This function copies the value in member parking_point1
             * @param _parking_point1 New value to be copied in member parking_point1
             */
            eProsima_user_DllExport void parking_point1(
                    const ros2_interface::msg::Point3D& _parking_point1);

            /*!
             * @brief This function moves the value in member parking_point1
             * @param _parking_point1 New value to be moved in member parking_point1
             */
            eProsima_user_DllExport void parking_point1(
                    ros2_interface::msg::Point3D&& _parking_point1);

            /*!
             * @brief This function returns a constant reference to member parking_point1
             * @return Constant reference to member parking_point1
             */
            eProsima_user_DllExport const ros2_interface::msg::Point3D& parking_point1() const;

            /*!
             * @brief This function returns a reference to member parking_point1
             * @return Reference to member parking_point1
             */
            eProsima_user_DllExport ros2_interface::msg::Point3D& parking_point1();
            /*!
             * @brief This function copies the value in member parking_point2
             * @param _parking_point2 New value to be copied in member parking_point2
             */
            eProsima_user_DllExport void parking_point2(
                    const ros2_interface::msg::Point3D& _parking_point2);

            /*!
             * @brief This function moves the value in member parking_point2
             * @param _parking_point2 New value to be moved in member parking_point2
             */
            eProsima_user_DllExport void parking_point2(
                    ros2_interface::msg::Point3D&& _parking_point2);

            /*!
             * @brief This function returns a constant reference to member parking_point2
             * @return Constant reference to member parking_point2
             */
            eProsima_user_DllExport const ros2_interface::msg::Point3D& parking_point2() const;

            /*!
             * @brief This function returns a reference to member parking_point2
             * @return Reference to member parking_point2
             */
            eProsima_user_DllExport ros2_interface::msg::Point3D& parking_point2();
            /*!
             * @brief This function copies the value in member parking_point3
             * @param _parking_point3 New value to be copied in member parking_point3
             */
            eProsima_user_DllExport void parking_point3(
                    const ros2_interface::msg::Point3D& _parking_point3);

            /*!
             * @brief This function moves the value in member parking_point3
             * @param _parking_point3 New value to be moved in member parking_point3
             */
            eProsima_user_DllExport void parking_point3(
                    ros2_interface::msg::Point3D&& _parking_point3);

            /*!
             * @brief This function returns a constant reference to member parking_point3
             * @return Constant reference to member parking_point3
             */
            eProsima_user_DllExport const ros2_interface::msg::Point3D& parking_point3() const;

            /*!
             * @brief This function returns a reference to member parking_point3
             * @return Reference to member parking_point3
             */
            eProsima_user_DllExport ros2_interface::msg::Point3D& parking_point3();

            /*!
             * @brief This function returns the maximum serialized size of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function returns the serialized size of a data depending on the buffer alignment.
             * @param data Data which is calculated its serialized size.
             * @param current_alignment Buffer alignment.
             * @return Serialized size.
             */
            eProsima_user_DllExport static size_t getCdrSerializedSize(
                    const ros2_interface::msg::UssParkingInfo& data,
                    size_t current_alignment = 0);


            /*!
             * @brief This function serializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serialize(
                    eprosima::fastcdr::Cdr& cdr) const;

            /*!
             * @brief This function deserializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void deserialize(
                    eprosima::fastcdr::Cdr& cdr);



            /*!
             * @brief This function returns the maximum serialized size of the Key of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                    size_t current_alignment = 0);

            /*!
             * @brief This function tells you if the Key has been defined for this type
             */
            eProsima_user_DllExport static bool isKeyDefined();

            /*!
             * @brief This function serializes the key members of an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serializeKey(
                    eprosima::fastcdr::Cdr& cdr) const;

        private:

            ros2_interface::msg::Header m_header;
            int32_t m_uss_parking_type;
            ros2_interface::msg::Point3D m_parking_point0;
            ros2_interface::msg::Point3D m_parking_point1;
            ros2_interface::msg::Point3D m_parking_point2;
            ros2_interface::msg::Point3D m_parking_point3;
        };
    } // namespace msg
} // namespace ros2_interface

#endif // _FAST_DDS_GENERATED_ROS2_INTERFACE_MSG_USSPARKINGINFO_H_