// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file UssParkingInfoList.cpp
 * This source file contains the definition of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifdef _WIN32
// Remove linker warning LNK4221 on Visual Studio
namespace {
char dummy;
}  // namespace
#endif  // _WIN32

#include "UssParkingInfoList.h"
#include <fastcdr/Cdr.h>

#include <fastcdr/exceptions/BadParamException.h>
using namespace eprosima::fastcdr::exception;

#include <utility>

ros2_interface::msg::UssParkingInfoList::UssParkingInfoList()
{
    // m_header com.eprosima.fastdds.idl.parser.typecode.StructTypeCode@61a91912

    // m_uss_parking_info com.eprosima.idl.parser.typecode.SequenceTypeCode@1763992e

    // m_error_code com.eprosima.idl.parser.typecode.PrimitiveTypeCode@5c92166b
    m_error_code = 0;
    // m_is_valid com.eprosima.idl.parser.typecode.PrimitiveTypeCode@659925f4
    m_is_valid = false;

}

ros2_interface::msg::UssParkingInfoList::~UssParkingInfoList()
{




}

ros2_interface::msg::UssParkingInfoList::UssParkingInfoList(
        const UssParkingInfoList& x)
{
    m_header = x.m_header;
    m_uss_parking_info = x.m_uss_parking_info;
    m_error_code = x.m_error_code;
    m_is_valid = x.m_is_valid;
}

ros2_interface::msg::UssParkingInfoList::UssParkingInfoList(
        UssParkingInfoList&& x)
{
    m_header = std::move(x.m_header);
    m_uss_parking_info = std::move(x.m_uss_parking_info);
    m_error_code = x.m_error_code;
    m_is_valid = x.m_is_valid;
}

ros2_interface::msg::UssParkingInfoList& ros2_interface::msg::UssParkingInfoList::operator =(
        const UssParkingInfoList& x)
{

    m_header = x.m_header;
    m_uss_parking_info = x.m_uss_parking_info;
    m_error_code = x.m_error_code;
    m_is_valid = x.m_is_valid;

    return *this;
}

ros2_interface::msg::UssParkingInfoList& ros2_interface::msg::UssParkingInfoList::operator =(
        UssParkingInfoList&& x)
{

    m_header = std::move(x.m_header);
    m_uss_parking_info = std::move(x.m_uss_parking_info);
    m_error_code = x.m_error_code;
    m_is_valid = x.m_is_valid;

    return *this;
}

bool ros2_interface::msg::UssParkingInfoList::operator ==(
        const UssParkingInfoList& x) const
{

    return (m_header == x.m_header && m_uss_parking_info == x.m_uss_parking_info && m_error_code == x.m_error_code && m_is_valid == x.m_is_valid);
}

bool ros2_interface::msg::UssParkingInfoList::operator !=(
        const UssParkingInfoList& x) const
{
    return !(*this == x);
}

size_t ros2_interface::msg::UssParkingInfoList::getMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t initial_alignment = current_alignment;


    current_alignment += ros2_interface::msg::Header::getMaxCdrSerializedSize(current_alignment);
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    for(size_t a = 0; a < 100; ++a)
    {
        current_alignment += ros2_interface::msg::UssParkingInfo::getMaxCdrSerializedSize(current_alignment);}

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);



    return current_alignment - initial_alignment;
}

size_t ros2_interface::msg::UssParkingInfoList::getCdrSerializedSize(
        const ros2_interface::msg::UssParkingInfoList& data,
        size_t current_alignment)
{
    (void)data;
    size_t initial_alignment = current_alignment;


    current_alignment += ros2_interface::msg::Header::getCdrSerializedSize(data.header(), current_alignment);
    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    for(size_t a = 0; a < data.uss_parking_info().size(); ++a)
    {
        current_alignment += ros2_interface::msg::UssParkingInfo::getCdrSerializedSize(data.uss_parking_info().at(a), current_alignment);}

    current_alignment += 4 + eprosima::fastcdr::Cdr::alignment(current_alignment, 4);


    current_alignment += 1 + eprosima::fastcdr::Cdr::alignment(current_alignment, 1);



    return current_alignment - initial_alignment;
}

void ros2_interface::msg::UssParkingInfoList::serialize(
        eprosima::fastcdr::Cdr& scdr) const
{

    scdr << m_header;
    scdr << m_uss_parking_info;
    scdr << m_error_code;
    scdr << m_is_valid;

}

void ros2_interface::msg::UssParkingInfoList::deserialize(
        eprosima::fastcdr::Cdr& dcdr)
{

    dcdr >> m_header;
    dcdr >> m_uss_parking_info;
    dcdr >> m_error_code;
    dcdr >> m_is_valid;
}

/*!
 * @brief This function copies the value in member header
 * @param _header New value to be copied in member header
 */
void ros2_interface::msg::UssParkingInfoList::header(
        const ros2_interface::msg::Header& _header)
{
    m_header = _header;
}

/*!
 * @brief This function moves the value in member header
 * @param _header New value to be moved in member header
 */
void ros2_interface::msg::UssParkingInfoList::header(
        ros2_interface::msg::Header&& _header)
{
    m_header = std::move(_header);
}

/*!
 * @brief This function returns a constant reference to member header
 * @return Constant reference to member header
 */
const ros2_interface::msg::Header& ros2_interface::msg::UssParkingInfoList::header() const
{
    return m_header;
}

/*!
 * @brief This function returns a reference to member header
 * @return Reference to member header
 */
ros2_interface::msg::Header& ros2_interface::msg::UssParkingInfoList::header()
{
    return m_header;
}
/*!
 * @brief This function copies the value in member uss_parking_info
 * @param _uss_parking_info New value to be copied in member uss_parking_info
 */
void ros2_interface::msg::UssParkingInfoList::uss_parking_info(
        const std::vector<ros2_interface::msg::UssParkingInfo>& _uss_parking_info)
{
    m_uss_parking_info = _uss_parking_info;
}

/*!
 * @brief This function moves the value in member uss_parking_info
 * @param _uss_parking_info New value to be moved in member uss_parking_info
 */
void ros2_interface::msg::UssParkingInfoList::uss_parking_info(
        std::vector<ros2_interface::msg::UssParkingInfo>&& _uss_parking_info)
{
    m_uss_parking_info = std::move(_uss_parking_info);
}

/*!
 * @brief This function returns a constant reference to member uss_parking_info
 * @return Constant reference to member uss_parking_info
 */
const std::vector<ros2_interface::msg::UssParkingInfo>& ros2_interface::msg::UssParkingInfoList::uss_parking_info() const
{
    return m_uss_parking_info;
}

/*!
 * @brief This function returns a reference to member uss_parking_info
 * @return Reference to member uss_parking_info
 */
std::vector<ros2_interface::msg::UssParkingInfo>& ros2_interface::msg::UssParkingInfoList::uss_parking_info()
{
    return m_uss_parking_info;
}
/*!
 * @brief This function sets a value in member error_code
 * @param _error_code New value for member error_code
 */
void ros2_interface::msg::UssParkingInfoList::error_code(
        int32_t _error_code)
{
    m_error_code = _error_code;
}

/*!
 * @brief This function returns the value of member error_code
 * @return Value of member error_code
 */
int32_t ros2_interface::msg::UssParkingInfoList::error_code() const
{
    return m_error_code;
}

/*!
 * @brief This function returns a reference to member error_code
 * @return Reference to member error_code
 */
int32_t& ros2_interface::msg::UssParkingInfoList::error_code()
{
    return m_error_code;
}

/*!
 * @brief This function sets a value in member is_valid
 * @param _is_valid New value for member is_valid
 */
void ros2_interface::msg::UssParkingInfoList::is_valid(
        bool _is_valid)
{
    m_is_valid = _is_valid;
}

/*!
 * @brief This function returns the value of member is_valid
 * @return Value of member is_valid
 */
bool ros2_interface::msg::UssParkingInfoList::is_valid() const
{
    return m_is_valid;
}

/*!
 * @brief This function returns a reference to member is_valid
 * @return Reference to member is_valid
 */
bool& ros2_interface::msg::UssParkingInfoList::is_valid()
{
    return m_is_valid;
}


size_t ros2_interface::msg::UssParkingInfoList::getKeyMaxCdrSerializedSize(
        size_t current_alignment)
{
    size_t current_align = current_alignment;







    return current_align;
}

bool ros2_interface::msg::UssParkingInfoList::isKeyDefined()
{
    return false;
}

void ros2_interface::msg::UssParkingInfoList::serializeKey(
        eprosima::fastcdr::Cdr& scdr) const
{
    (void) scdr;
        
}


