/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#ifndef __lcm_interface_CameraParkingInfoList_hpp__
#define __lcm_interface_CameraParkingInfoList_hpp__

#include <lcm/lcm_coretypes.h>

#include <vector>
#include "lcm_interface/Header.hpp"
#include "lcm_interface/CameraParkingInfo.hpp"
#include "lcm_interface/CameraParkingStopper.hpp"

namespace lcm_interface
{

/// CameraParkingInfoList::CameraParkingInfoList
class CameraParkingInfoList
{
    public:
        lcm_interface::Header header;

        /// 消息头，时间戳使用接收的图像的时间戳
        int32_t    sensor_id;

        /// 安装的传感器id(camera,lidar,radar) ' 相机id: 0-front_center相机 1-front_left相机 2-front_right相机 3-left_front相机 4-left_back右后相机 5-right_front相机 6-right_back相机 7-back相机'  8-相机融合
        int32_t    camera_parking_size;

        std::vector< lcm_interface::CameraParkingInfo > camera_parking;

        /// 检测出的障碍物数组
        int32_t    camera_parking_stoppers_size;

        std::vector< lcm_interface::CameraParkingStopper > camera_parking_stoppers;

        /// 检测出的限位器数组
        int32_t    error_code;

        /// 错误码（default = OK）
        int8_t     is_valid;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "CameraParkingInfoList"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int CameraParkingInfoList::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int CameraParkingInfoList::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int CameraParkingInfoList::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t CameraParkingInfoList::getHash()
{
    static int64_t hash = static_cast<int64_t>(_computeHash(NULL));
    return hash;
}

const char* CameraParkingInfoList::getTypeName()
{
    return "CameraParkingInfoList";
}

int CameraParkingInfoList::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = this->header._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->sensor_id, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->camera_parking_size, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->camera_parking_size; a0++) {
        tlen = this->camera_parking[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->camera_parking_stoppers_size, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->camera_parking_stoppers_size; a0++) {
        tlen = this->camera_parking_stoppers[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->error_code, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &this->is_valid, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int CameraParkingInfoList::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = this->header._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->sensor_id, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->camera_parking_size, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    try {
        this->camera_parking.resize(this->camera_parking_size);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->camera_parking_size; a0++) {
        tlen = this->camera_parking[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->camera_parking_stoppers_size, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    try {
        this->camera_parking_stoppers.resize(this->camera_parking_stoppers_size);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->camera_parking_stoppers_size; a0++) {
        tlen = this->camera_parking_stoppers[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->error_code, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &this->is_valid, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int CameraParkingInfoList::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += this->header._getEncodedSizeNoHash();
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->camera_parking_size; a0++) {
        enc_size += this->camera_parking[a0]._getEncodedSizeNoHash();
    }
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->camera_parking_stoppers_size; a0++) {
        enc_size += this->camera_parking_stoppers[a0]._getEncodedSizeNoHash();
    }
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    return enc_size;
}

uint64_t CameraParkingInfoList::_computeHash(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == CameraParkingInfoList::getHash)
            return 0;
    const __lcm_hash_ptr cp = { p, CameraParkingInfoList::getHash };

    uint64_t hash = 0x4c2ee6486a2fa6e9LL +
         lcm_interface::Header::_computeHash(&cp) +
         lcm_interface::CameraParkingInfo::_computeHash(&cp) +
         lcm_interface::CameraParkingStopper::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
