/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#ifndef __lcm_interface_ObstacleFeature_hpp__
#define __lcm_interface_ObstacleFeature_hpp__

#include <lcm/lcm_coretypes.h>

#include <vector>
#include "lcm_interface/Point3D.hpp"
#include "lcm_interface/Point3D.hpp"
#include "lcm_interface/Point3D.hpp"
#include "lcm_interface/Point3D.hpp"
#include "lcm_interface/Point3D.hpp"
#include "lcm_interface/Point3D.hpp"
#include "lcm_interface/Point3D.hpp"
#include "lcm_interface/Point3D.hpp"
#include "lcm_interface/Point3D.hpp"
#include "lcm_interface/ObstaclePriority.hpp"
#include "lcm_interface/PredictionTrajectoryPoint.hpp"
#include "lcm_interface/TrajectoryPointInPrediction.hpp"
#include "lcm_interface/TrajectoryInPrediction.hpp"
#include "lcm_interface/TrajectoryPointInPrediction.hpp"

namespace lcm_interface
{

/// ObstacleFeature::ObstacleFeature
class ObstacleFeature
{
    public:
        int32_t    obstacle_id;

        /// Obstacle ID
        lcm_interface::Point3D polygon_point;

        /// 障碍物边框点列
        lcm_interface::Point3D position;

        /**
         */
        lcm_interface::Point3D front_position;

        /**
         */
        lcm_interface::Point3D velocity;

        /**
         */
        lcm_interface::Point3D raw_velocity;

        /// from perception
        lcm_interface::Point3D acceleration;

        /**
         */
        double     velocity_heading;

        /**
         */
        double     speed;

        /**
         */
        double     acc;

        /**
         */
        double     theta;

        /**
         */
        double     length;

        /**
         */
        double     width;

        /**
         */
        double     height;

        /**
         */
        double     tracking_time;

        /**
         */
        double     timestamp;

        /**
         */
        lcm_interface::Point3D t_position;

        /**
         */
        lcm_interface::Point3D t_velocity;

        /// [deprecated = true]
        double     t_velocity_heading;

        /// [deprecated = true]
        double     t_speed;

        /// [deprecated = true]
        lcm_interface::Point3D t_acceleration;

        /// [deprecated = true]
        double     t_acc;

        /// [deprecated = true]
        int8_t     is_still;

        /// [deprecated = false]
        int32_t    type;

        /// 感知到的障碍物类型         0-UNKNOWN, 1-UNKNOWN_MOVABLE, 2-UNKNOWN_UNMOVABLE, 3-PEDESTRIAN, 4-BICYCLE,     5-VEHICLE
        double     label_update_time_delta;

        /**
         */
        lcm_interface::ObstaclePriority priority;

        /// CAUTION = 1; NORMAL = 2; IGNORE = 3;
        int8_t     is_near_junction;

        /**
         */
        int32_t    future_trajectory_points_size;

        std::vector< lcm_interface::PredictionTrajectoryPoint > future_trajectory_points;

        /// Obstacle ground-truth labels:
        int32_t    short_term_predicted_trajectory_points_size;

        std::vector< lcm_interface::TrajectoryPointInPrediction > short_term_predicted_trajectory_points;

        /// Obstacle short-term predicted trajectory points
        int32_t    predicted_trajectory_size;

        std::vector< lcm_interface::TrajectoryInPrediction > predicted_trajectory;

        /// Obstacle predicted trajectories
        int32_t    adc_trajectory_point_size;

        std::vector< lcm_interface::TrajectoryPointInPrediction > adc_trajectory_point;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "ObstacleFeature"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int ObstacleFeature::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int ObstacleFeature::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int ObstacleFeature::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t ObstacleFeature::getHash()
{
    static int64_t hash = static_cast<int64_t>(_computeHash(NULL));
    return hash;
}

const char* ObstacleFeature::getTypeName()
{
    return "ObstacleFeature";
}

int ObstacleFeature::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->obstacle_id, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->polygon_point._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->position._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->front_position._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->velocity._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->raw_velocity._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->acceleration._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->velocity_heading, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->speed, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->acc, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->theta, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->length, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->width, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->height, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->tracking_time, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->timestamp, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->t_position._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->t_velocity._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->t_velocity_heading, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->t_speed, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->t_acceleration._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->t_acc, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &this->is_still, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->type, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->label_update_time_delta, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->priority._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_encode_array(buf, offset + pos, maxlen - pos, &this->is_near_junction, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->future_trajectory_points_size, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->future_trajectory_points_size; a0++) {
        tlen = this->future_trajectory_points[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->short_term_predicted_trajectory_points_size, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->short_term_predicted_trajectory_points_size; a0++) {
        tlen = this->short_term_predicted_trajectory_points[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->predicted_trajectory_size, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->predicted_trajectory_size; a0++) {
        tlen = this->predicted_trajectory[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->adc_trajectory_point_size, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->adc_trajectory_point_size; a0++) {
        tlen = this->adc_trajectory_point[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int ObstacleFeature::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->obstacle_id, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->polygon_point._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->position._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->front_position._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->velocity._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->raw_velocity._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->acceleration._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->velocity_heading, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->speed, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->acc, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->theta, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->length, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->width, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->height, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->tracking_time, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->timestamp, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->t_position._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->t_velocity._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->t_velocity_heading, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->t_speed, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->t_acceleration._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->t_acc, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &this->is_still, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->type, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->label_update_time_delta, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->priority._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __boolean_decode_array(buf, offset + pos, maxlen - pos, &this->is_near_junction, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->future_trajectory_points_size, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    try {
        this->future_trajectory_points.resize(this->future_trajectory_points_size);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->future_trajectory_points_size; a0++) {
        tlen = this->future_trajectory_points[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->short_term_predicted_trajectory_points_size, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    try {
        this->short_term_predicted_trajectory_points.resize(this->short_term_predicted_trajectory_points_size);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->short_term_predicted_trajectory_points_size; a0++) {
        tlen = this->short_term_predicted_trajectory_points[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->predicted_trajectory_size, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    try {
        this->predicted_trajectory.resize(this->predicted_trajectory_size);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->predicted_trajectory_size; a0++) {
        tlen = this->predicted_trajectory[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->adc_trajectory_point_size, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    try {
        this->adc_trajectory_point.resize(this->adc_trajectory_point_size);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->adc_trajectory_point_size; a0++) {
        tlen = this->adc_trajectory_point[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int ObstacleFeature::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += this->polygon_point._getEncodedSizeNoHash();
    enc_size += this->position._getEncodedSizeNoHash();
    enc_size += this->front_position._getEncodedSizeNoHash();
    enc_size += this->velocity._getEncodedSizeNoHash();
    enc_size += this->raw_velocity._getEncodedSizeNoHash();
    enc_size += this->acceleration._getEncodedSizeNoHash();
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += this->t_position._getEncodedSizeNoHash();
    enc_size += this->t_velocity._getEncodedSizeNoHash();
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += this->t_acceleration._getEncodedSizeNoHash();
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += this->priority._getEncodedSizeNoHash();
    enc_size += __boolean_encoded_array_size(NULL, 1);
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->future_trajectory_points_size; a0++) {
        enc_size += this->future_trajectory_points[a0]._getEncodedSizeNoHash();
    }
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->short_term_predicted_trajectory_points_size; a0++) {
        enc_size += this->short_term_predicted_trajectory_points[a0]._getEncodedSizeNoHash();
    }
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->predicted_trajectory_size; a0++) {
        enc_size += this->predicted_trajectory[a0]._getEncodedSizeNoHash();
    }
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->adc_trajectory_point_size; a0++) {
        enc_size += this->adc_trajectory_point[a0]._getEncodedSizeNoHash();
    }
    return enc_size;
}

uint64_t ObstacleFeature::_computeHash(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == ObstacleFeature::getHash)
            return 0;
    const __lcm_hash_ptr cp = { p, ObstacleFeature::getHash };

    uint64_t hash = 0x5901cdda69762b34LL +
         lcm_interface::Point3D::_computeHash(&cp) +
         lcm_interface::Point3D::_computeHash(&cp) +
         lcm_interface::Point3D::_computeHash(&cp) +
         lcm_interface::Point3D::_computeHash(&cp) +
         lcm_interface::Point3D::_computeHash(&cp) +
         lcm_interface::Point3D::_computeHash(&cp) +
         lcm_interface::Point3D::_computeHash(&cp) +
         lcm_interface::Point3D::_computeHash(&cp) +
         lcm_interface::Point3D::_computeHash(&cp) +
         lcm_interface::ObstaclePriority::_computeHash(&cp) +
         lcm_interface::PredictionTrajectoryPoint::_computeHash(&cp) +
         lcm_interface::TrajectoryPointInPrediction::_computeHash(&cp) +
         lcm_interface::TrajectoryInPrediction::_computeHash(&cp) +
         lcm_interface::TrajectoryPointInPrediction::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
