 #ifndef __ControlAnalysis__idl__
#define __ControlAnalysis__idl__
#include "Header.idl"
module ros2_interface{
 module msg{
  struct ControlAnalysis{
    ros2_interface::msg::Header   _header;
    int32   _driving_mode;
    int32   _driving_mode_fd;
    int32   _gear_location_fd;
    int32   _gear_location_cmd;
    int32   _epb_level_fd;
    int32   _epb_level_cmd;
    double   _speed_mps;
    double   _speed_reference;
    double   _accel_value_fd;
    double   _accel_value_cmd;
    double   _brake_value_fd;
    double   _brake_value_cmd;
    double   _path_remain;
    boolean   _has_stop_point;
    boolean   _is_full_stop;
    boolean   _is_stopped;
    double   _lon_acc_jerk;
    double   _acceleration_cmd;
    double   _acceleration_cmd_closeloop;
    double   _preview_acceleration_reference;
    double   _slope_offset_compensation;
    double   _turning_offset_compensation;
    double   _speed_error_limited;
    double   _speed_error;
    double   _speed_offset;
    double   _station_error_limited;
    double   _station_error;
    double   _lon_target_point_s;
    int64   _lon_calculate_time;
    int64   _lon_calculate_time_max;
    double   _ref_curvature;
    double   _ref_heading;
    double   _current_heading;
    double   _heading_error;
    double   _heading_error_rate;
    double   _lateral_error;
    double   _lateral_error_rate;
    double   _lon_error;
    double   _front_steering_value_fd;
    double   _front_steering_target;
    double   _front_steering_rate;
    double   _front_steer_angle_feedforward;
    double   _front_steer_angle_feedback;
    double   _front_steer_angle_lateral_contribution;
    double   _front_steer_angle_lateral_rate_contribution;
    double   _front_steer_angle_heading_contribution;
    double   _front_steer_angle_heading_rate_contribution;
    double   _rear_steering_value_fd;
    double   _rear_steering_target;
    double   _rear_steering_rate;
    double   _rear_steer_angle_feedforward;
    double   _rear_steer_angle_feedback;
    double   _rear_steer_angle_lateral_contribution;
    double   _rear_steer_angle_lateral_rate_contribution;
    double   _rear_steer_angle_heading_contribution;
    double   _rear_steer_angle_heading_rate_contribution;
    double   _matrix_k_00;
    double   _matrix_k_01;
    double   _matrix_k_02;
    double   _matrix_k_03;
    double   _matrix_k_10;
    double   _matrix_k_11;
    double   _matrix_k_12;
    double   _matrix_k_13;
    double   _matrix_state_0;
    double   _matrix_state_1;
    double   _matrix_state_2;
    double   _matrix_state_3;
    double   _matrix_q_updated_0;
    double   _matrix_q_updated_1;
    double   _matrix_q_updated_2;
    double   _matrix_q_updated_3;
    double   _current_x;
    double   _current_y;
    double   _target_point_x;
    double   _target_point_y;
    double   _lat_target_point_s;
    int64   _lqr_calculate_time;
    int64   _lqr_calculate_time_max;
  };
 };
}; 
#endif