 #ifndef __Header__idl__
#define __Header__idl__
#include "Time.idl"
module ros2_interface{
 module msg{
  struct Header{
    uint32   _seq;
    ros2_interface::msg::Time   _stamp;
    string   _frame_id;
  };
 };
}; 
#endif