 #ifndef __ObuCmdMsg__idl__
#define __ObuCmdMsg__idl__
#include "Header.idl"
#include "ObuCmd.idl"
module ros2_interface{
 module msg{
  struct ObuCmdMsg{
    ros2_interface::msg::Header   _header;
    int32   _id;
    string   _name;
    sequence<ros2_interface::msg::ObuCmd> _obu_cmd_list;
  };
 };
}; 
#endif