
/**
 * @file lon_controller.h
 * @author jiang <jiangchengjie@indrv.cn>
 * @date  2018-07-07
 * @version 1.0.0
 * @par  Copyright(c)
 *        hy
 */

#pragma once

#include <fstream>
#include <memory>
#include <string>
#include <vector>

#include "lon_dynamics.hpp"
#include "controller/controller.h"
#include "controller/pid/pid_controller.h"
#include "gear_state_machine_debug.hpp"
#include "simple_longitudinal_debug.hpp"
#include "controller/leadlag_controller/leadlag_controller.h"

#include "modules/control/src/common/control_gflags.h"
#include "modules/control/src/common/interpolation_2d.h"
#include "modules/control/src/common/filters/digital_filter.h"
#include "modules/control/src/common/filters/digital_filter_coefficients.h"
#include "modules/control/src/common/trajectory_analyzer/trajectory_analyzer.h"

#include "modules/common/timer/timer_manager.h"
#include "modules/common/timer/ad_timer_manager.h"
#include "modules/common/state_machine/state_context.hpp"
#include "modules/control/src/common/local_view.h"

using legionclaw::common::state_machine::StateContext;

/**
 * @namespace legionclaw::control
 * @brief legionclaw::control
 */
namespace legionclaw {
namespace control {

/**
 * @class LonController
 *
 * @brief Longitudinal controller, to compute brake / throttle values.
 */
class LonController : public Controller {
 public:
  /**
   * @brief constructor
   */
  LonController();

  /**
   * @brief destructor
   */
  virtual ~LonController();

  typedef enum {
    SUCCESS = 0,
    FAILED = 1,
    TRANSITIONING = 2,
  } GearTransState;

  /**
   * @brief init.
   * @param[in] control_conf control configurations
   * @return Status initialization status.
   */
  legionclaw::common::Status Init(std::shared_ptr<DependencyInjector> injector,
                              const ControlConf *control_conf) override;

  /**
   * @brief compute control command based on current vehicle status
   *        and target trajectory
   * @param localization vehicle location
   * @param chassis vehicle status e.g., speed, acceleration
   * @param trajectory trajectory generated by planning
   * @param cmd control command
   * @return Status computation status
   */
  legionclaw::common::Status ComputeControlCommand(
      const legionclaw::interface::LocalizationEstimate *localization,
      const legionclaw::interface::Chassis *chassis,
      const legionclaw::interface::ADCTrajectory *trajectory,
      legionclaw::interface::ControlCommand *cmd,
      legionclaw::interface::ControlAnalysis *analysis) override;

  /**
   * @brief reset Lateral Controller
   * @return Status reset status
   */
  legionclaw::common::Status Reset() override;

  /**
   * @brief stop Lateral controller
   */
  void Stop() override;

  /**
   * @brief Lateral controller name
   * @return string controller name in string
   */
  std::string Name() const override;

 protected:
  void ComputeLongitudinalErrors(
      const TrajectoryAnalyzer *trajectory,
      const legionclaw::interface::LocalizationEstimate *localization,
      const legionclaw::interface::Chassis *chassis, const double preview_time,
      const double ts, SimpleLongitudinalDebug *debug);

  void GetPathRemain(SimpleLongitudinalDebug *debug);

  void SetAnalysis(const legionclaw::interface::ControlCommand *cmd,
                   const SimpleLongitudinalDebug *debug,
                   const legionclaw::interface::Chassis *chassis,
                   legionclaw::interface::ControlAnalysis *analysis);

 protected:
  void SetDigitalFilterPitchAngle(const LonControllerConf &lon_controller_conf);

  void LoadControlCalibrationTable(
      const LonControllerConf &lon_controller_conf);

  void SetDigitalFilter(double ts, double cutoff_freq,
                        common::DigitalFilter *digital_filter);
  std::string GetLogFileName();
  void WriteHeaders(std::ofstream &file_stream);
  void CloseLogFile();

  void Impulse(const DownhillSceneConf &downhill_scene_conf,
               const double &pitch, double &brake_cmd, double &throttle_cmd);

  void IdleSpeedControlOfOilCar(const double &speed_reference,
                                double &deceleration_in_idle,
                                double &acceleration_lookup,
                                double &output_value);

  const legionclaw::interface::LocalizationEstimate *localization_ = nullptr;
  const legionclaw::interface::Chassis *chassis_ = nullptr;

  std::unique_ptr<Interpolation2D> control_interpolation_;
  const legionclaw::interface::ADCTrajectory *trajectory_message_ = nullptr;
  std::unique_ptr<TrajectoryAnalyzer> trajectory_analyzer_;

  std::string name_;
  bool controller_initialized_ = false;
  double previous_acceleration_ = 0.0;
  double previous_acceleration_reference_ = 0.0;
  double previous_acceleration_cmd_ = 0.0;
  double previous_timestamp_ = 0.0;
  double calculate_period_ = 0.0;
  int64_t lon_calculate_time_ = 0;
  int64_t lon_calculate_time_max_ = 0;
  double trajectory_update_duration_ = 0.0;
  bool trajectory_update_flag_ = false;

  PIDController speed_pid_controller_;
  PIDController station_pid_controller_;

  LeadlagController speed_leadlag_controller_;
  LeadlagController station_leadlag_controller_;

  std::ofstream speed_log_file_;

  common::DigitalFilter digital_filter_pitch_angle_;

  const ControlConf *control_conf_ = nullptr;

  bool use_new_planning_mode_ = false;
  bool use_acceleration_mode_ = false;
  bool use_deceleration_mode_ = false;
  uint8_t state_machine = 0;
  double add_lr_ = 0.0;

  double mass_;
  double steer_ratio_;
  double lr_;
  double lf_;
  double wheelbase_;

  // vehicle parameter
  VehicleParam vehicle_param_;
  int brake_sign_;
  double brake_delay_time_;
  double vehicle_speed_in_idle_;
  double deceleration_in_idle_speed_;
  double starting_acceleration_in_d_;
  double starting_acceleration_in_r_;
  double kp_brake_;
  double starting_speed_;
  double pitch_offset_;
  double speed_limit_;
  double max_max_acceleration_;
  double max_deceleration_;
  double max_acceleration_jerk_;
  double standstill_acceleration_;
  bool enable_log_debug_;
  bool lon_print_enable_;
  bool enable_speed_station_preview_ = false;
  bool enable_slope_offset_ = true;
  bool enable_aero_offset_ = true;
  bool enable_turning_offset_ = true;
  bool enable_rolling_offset_ = true;
  bool use_preview_speed_for_table_ = false;
  bool query_forward_time_point_only = false;
  bool use_calibration_table_;
  double accel_value_kp_;
  double max_accel_value_;
  std::shared_ptr<SimpleLongitudinalDebug> simple_longitudinal_debug_;
  std::unique_ptr<LonDynamics> lon_dynamics_;
  std::shared_ptr<DependencyInjector> injector_;

 protected:
  std::shared_ptr<state_machine::StateContext> gear_sm_;
  std::shared_ptr<state_machine::StateContext> epb_sm_;

  void StateMachineSpin(void *param);

  GearStateMachineDebug gear_sm_debug_;
  GearTransState gear_trans_state_;

  void GearTransitionInit();

  void GearTransition(legionclaw::interface::ControlCommand *cmd);

  void GearInitEntry(const std::string &state_name, int state);
  void GearInitUpdate(const std::string &state_name, int state);
  void GearNEntry(const std::string &state_name, int state);
  void GearNUpdate(const std::string &state_name, int state);
  void GearNExit(const std::string &state_name, int state);
  void GearDEntry(const std::string &state_name, int state);
  void GearDUpdate(const std::string &state_name, int state);
  void GearDExit(const std::string &state_name, int state);
  void GearREntry(const std::string &state_name, int state);
  void GearRUpdate(const std::string &state_name, int state);
  void GearRExit(const std::string &state_name, int state);
  void EPBInitEntry(const std::string &state_name, int state);
  void EPBInitUpdate(const std::string &state_name, int state);
  void EPBAppliedEntry(const std::string &state_name, int state);
  void EPBAppliedUpdate(const std::string &state_name, int state);
  void EPBAppliedExit(const std::string &state_name, int state);
  void EPBReleaseEntry(const std::string &state_name, int state);
  void EPBReleaseUpdate(const std::string &state_name, int state);
  void EPBReleaseExit(const std::string &state_name, int state);

 protected:
  double ts_ = 0.02;
  bool is_stopped_;
  bool is_stopped_first_hit_;
  bool is_in_brake_;
  int64_t last_time_vehicle_is_stopped_or_not_;
  bool enable_epb_applied_;
  bool is_enable_epb_applied_first_hit_;
  int64_t last_time_enable_epb_applied_;
  std::map<std::string, bool> EventFlags;
  double last_accel_value_ = 0.0;

  void SetEventFlag(std::string key, bool value) { EventFlags[key] = value; }

  bool IsEventFlagTrue(std::string key) {
    if (EventFlags.count(key) == 0) {
      EventFlags[key] = false;
    }
    return EventFlags[key];
  }
};
}  // namespace control
}  // namespace legionclaw
